const express = require('express');
const jwt = require('jsonwebtoken');
const db = require('../db');


//THIS FUNCTIONS RUNS BEFORE EVERY REQUEST SENT TO THE /api/* ROUTE
async function jwtAuthCookie(req, res, next){
//Stores the Current token, sent along with the request as a cookie,
//  this cookie was previously generated by this backend upon successful login
    const token = req.cookies.token;
//Verifies if the token matches the one sent by our backend upon logging in,


    try {

        jwt.verify(token,process.env.JWT_SECRET)
        next();
//if it is not, an error is thrown
    } catch(err){
//if this error is an expired token error we request a new token using the reftoken,
//also stored as a cookie passed down from the login request
        if (err.name == "TokenExpiredError" ){
        const reftoken = req.cookies.reftoken;
  
        const queryResponse = await db.query(`SELECT * FROM usuarios WHERE uid = $1`,[jwt.decode(token).sub]);
        const queryData = queryResponse.rows;
//If the reftoken matches the one in the DB, a new JWT is issued and the Request follows it's intended path
        if (reftoken == queryData[0].reftoken){
            const newToken = jwt.sign({
                    sub : queryData[0].uid,
                    iss : 'SimpleERP',
                    role: queryData[0].permissao
                }, process.env.JWT_SECRET, {expiresIn: '5m'})
            
                res.cookie('token',newToken,{httpOnly:true});
                next();

//If it does not match, however, the error is an expired reftoken,
//in which case the user must log in again
        } else {
            res.status(401).send(err.name);
            res.clearCookie('token');
            res.clearCookie('reftoken');
        }
    }
//If the Error was not related to an expired JWT, send the error as a response to be handled by the backend
    else{
        res.status(401).send(err.name);
        res.clearCookie('token');
    }

        

    }


}

exports = jwtAuthCookie;
